const data = [
  {
    SL: 1,
    ID: "EMP-001",
    Name: "Abdul Rahman",
    Email: "abdul.rahman@gmail.com",
    Branch: "Main Branch",
    District: "Dhaka",
    Area: "Mirpur",
    Salary: "৳45,000",
    Status: "Active",
  },
  {
    SL: 2,
    ID: "EMP-002",
    Name: "Fatima Begum",
    Email: "fatima.begum@yahoo.com",
    Branch: "Sub Branch",
    District: "Chittagong",
    Area: "Agrabad",
    Salary: "৳38,000",
    Status: "Inactive",
  },
  {
    SL: 3,
    ID: "EMP-003",
    Name: "Mohammad Ali",
    Email: "mohammad.ali@hotmail.com",
    Branch: "Regional Branch",
    District: "Sylhet",
    Area: "Zindabazar",
    Salary: "৳42,000",
    Status: "Active",
  },
  {
    SL: 4,
    ID: "EMP-004",
    Name: "Ayesha Akhtar",
    Email: "ayesha.akhtar@gmail.com",
    Branch: "Main Branch",
    District: "Dhaka",
    Area: "Gulshan",
    Salary: "৳50,000",
    Status: "Active",
  },
  {
    SL: 5,
    ID: "EMP-005",
    Name: "Kamal Hossain",
    Email: "kamal.hossain@yahoo.com",
    Branch: "Sub Branch",
    District: "Khulna",
    Area: "Sonadanga",
    Salary: "৳35,000",
    Status: "Inactive",
  },
];
