export const data = [
  {
    SL: 1,
    Name: "Abdul Rahman",
    Email: "abdul.rahman@gmail.com",
    Address: "House 12, Road 5, Dhanmondi, Dhaka",
    Type: "Residential",
    District: "Dhaka",
    Area: "Dhanmondi",
    Status: "Active",
  },
  {
    SL: 2,
    Name: "Fatima Begum",
    Email: "fatima.begum@yahoo.com",
    Address: "Flat 3B, Road 8, Gulshan, Dhaka",
    Type: "Commercial",
    District: "Dhaka",
    Area: "Gulshan",
    Status: "Inactive",
  },
  {
    SL: 3,
    Name: "Mohammad Ali",
    Email: "mohammad.ali@hotmail.com",
    Address: "House 45, Road 3, Mirpur, Dhaka",
    Type: "Residential",
    District: "Dhaka",
    Area: "Mirpur",
    Status: "Active",
  },
  {
    SL: 4,
    Name: "Ayesha Akhtar",
    Email: "ayesha.akhtar@gmail.com",
    Address: "House 23, Road 7, Uttara, Dhaka",
    Type: "Residential",
    District: "Dhaka",
    Area: "Uttara",
    Status: "Active",
  },
  {
    SL: 5,
    Name: "Kamal Hossain",
    Email: "kamal.hossain@yahoo.com",
    Address: "House 34, Road 2, Banani, Dhaka",
    Type: "Commercial",
    District: "Dhaka",
    Area: "Banani",
    Status: "Inactive",
  },
];
