export const data = [
  {
    SL: 1,
    ID: "M-0540",
    JoiningDate: "2023-01-15",
    CompanyName: "ABC Ltd.",
    Name: "Lindsay Walton",
    avatar: "",
    Email: "ken99@yahoo.com",
    ContactNumber: "+8801712345678",
    Branch: "Dhaka",
    COD: "Cash on Delivery",
    Area: "Gulshan",
    District: "Dhaka",
    Status: "active",
  },
  {
    SL: 2,
    ID: "M-0540",
    JoiningDate: "2023-02-20",
    CompanyName: "XYZ Corporation",
    Name: "Lindsay Walton",
    avatar: "",
    Email: "ken99@yahoo.com",
    ContactNumber: "+8801812345678",
    Branch: "Chittagong",
    COD: "Online Payment",
    Area: "Agrabad",
    District: "Chittagong",
    Status: "active",
  },
  {
    SL: 3,
    ID: "M-0540",
    JoiningDate: "2023-03-25",
    CompanyName: "DEF Enterprises",
    Name: "Lindsay Walton",
    avatar: "",
    Email: "ken99@yahoo.com",
    ContactNumber: "+8801912345678",
    Branch: "Sylhet",
    COD: "Cash on Delivery",
    Area: "Zindabazar",
    District: "Sylhet",
    Status: "active",
  },
  {
    SL: 4,
    ID: "M-0540",
    JoiningDate: "2023-04-30",
    CompanyName: "GHI Industries",
    Name: "Lindsay Walton",
    avatar: "",
    Email: "ken99@yahoo.com",
    ContactNumber: "+8801512345678",
    Branch: "Khulna",
    COD: "Online Payment",
    Area: "Sonadanga",
    District: "Khulna",
    Status: "inactive",
  },
];
