export const data = [
  {
    SL: 1,
    ServiceArea: "House 12, Road 5, Dhanmondi, Dhaka",
    Title: "Domestic Parcel Delivery",
    Rate: "Express Delivery",
    Area: "Dhanmondi",
    Status: "Active",
  },
  {
    SL: 2,
    ServiceArea: "Plot 23, Block C, Bashundhara R/A, Dhaka",
    Title: "Corporate Document Courier",
    Rate: "Same-Day Delivery",
    Area: "Bashundhara",
    Status: "Active",
  },
  {
    SL: 3,
    ServiceArea: "Shop 45, Mirpur-10, Dhaka",
    Title: "E-Commerce Package Delivery",
    Rate: "Cash on Delivery (COD)",
    Area: "Mirpur",
    Status: "Active",
  },
  {
    SL: 4,
    ServiceArea: "House 78, Road 9, Uttara, Dhaka",
    Title: "International Shipment",
    Rate: "Customs Handling Fee",
    Area: "Uttara",
    Status: "Active",
  },
  {
    SL: 5,
    ServiceArea: "Chittagong Port Area, Chittagong",
    Title: "Bulk Cargo Delivery",
    Rate: "Heavy Load Handling",
    Area: "Chittagong Port",
    Status: "Inactive",
  },
];
