export const data = [
  {
    SL: 1,
    District: "Rajshahi",
    Division: "Rajshahi",
    Zone: "North-West",
    Country: "Bangladesh",
  },
  {
    SL: 2,
    District: "Barisal",
    Division: "Barisal",
    Zone: "South-Central",
    Country: "Bangladesh",
  },
  {
    SL: 3,
    District: "Dhaka",
    Division: "Dhaka",
    Zone: "Central",
    Country: "Bangladesh",
  },
  {
    SL: 4,
    District: "Chattogram",
    Division: "Chattogram",
    Zone: "South-East",
    Country: "Bangladesh",
  },
  {
    SL: 5,
    District: "Cumilla",
    Division: "Chittagong",
    Zone: "South-East",
    Country: "Bangladesh",
  },
  {
    SL: 6,
    District: "Sylhet",
    Division: "Sylhet",
    Zone: "North-East",
    Country: "Bangladesh",
  },
  {
    SL: 7,
    District: "Khulna",
    Division: "Khulna",
    Zone: "South-West",
    Country: "Bangladesh",
  },
  {
    SL: 8,
    District: "Rangpur",
    Division: "Rangpur",
    Zone: "North-West",
    Country: "Bangladesh",
  },
  {
    SL: 9,
    District: "Mymensingh",
    Division: "Mymensingh",
    Zone: "North-Central",
    Country: "Bangladesh",
  },
];
