export const data = [
  {
    SL: 1,
    Name: "Abdul Rahman",
    Email: "abdul.rahman@gmail.com",
    Branch: "Main Branch",
    District: "Dhaka",
    Area: "Mirpur",
    Status: "Active",
  },
  {
    SL: 2,
    Name: "Fatima Begum",
    Email: "fatima.begum@yahoo.com",
    Branch: "Sub Branch",
    District: "Chittagong",
    Area: "Agrabad",
    Status: "Inactive",
  },
  {
    SL: 3,
    Name: "Mohammad Ali",
    Email: "mohammad.ali@hotmail.com",
    Branch: "Regional Branch",
    District: "Sylhet",
    Area: "Zindabazar",
    Status: "Active",
  },
  {
    SL: 4,
    Name: "Ayesha Akhtar",
    Email: "ayesha.akhtar@gmail.com",
    Branch: "Main Branch",
    District: "Dhaka",
    Area: "Gulshan",
    Status: "Active",
  },
  {
    SL: 5,
    Name: "Kamal Hossain",
    Email: "kamal.hossain@yahoo.com",
    Branch: "Sub Branch",
    District: "Khulna",
    Area: "Sonadanga",
    Status: "Inactive",
  },
  {
    SL: 6,
    Name: "Rahim Khan",
    Email: "rahim.khan@gmail.com",
    Branch: "Regional Branch",
    District: "Rajshahi",
    Area: "Shaheb Bazar",
    Status: "Active",
  },
  {
    SL: 7,
    Name: "Sadia Islam",
    Email: "sadia.islam@yahoo.com",
    Branch: "Main Branch",
    District: "Barishal",
    Area: "Sadar Road",
    Status: "Inactive",
  },
  {
    SL: 8,
    Name: "Nazmul Hasan",
    Email: "nazmul.hasan@gmail.com",
    Branch: "Sub Branch",
    District: "Rangpur",
    Area: "Station Road",
    Status: "Active",
  },
  {
    SL: 9,
    Name: "Tasnim Ahmed",
    Email: "tasnim.ahmed@hotmail.com",
    Branch: "Regional Branch",
    District: "Mymensingh",
    Area: "Kewatkhali",
    Status: "Inactive",
  },
  {
    SL: 10,
    Name: "Farhana Akhter",
    Email: "farhana.akhter@gmail.com",
    Branch: "Main Branch",
    District: "Comilla",
    Area: "Kandirpar",
    Status: "Active",
  },
];
